### ISSUE TITLE
Maybe a few things before we are ready to go :)

### ISSUE THREAD

**Issue by jedisct1** [x13a/zig-scrypt#4]
A few things we may want to address before submitting this as a PR for the standard library:

- Check on different platforms (32 bit, 64 bit, little and big endian, WebAssembly).
- Add more test vectors
- Add it to `crypto/benchmark.zig`
- Maybe put everything in a single file (perhaps not the PHC serialization)
- Make `fromPhcString` more strict, return `ParseError` if parameters are missing
- Remove `init()` when no allocator is required (ex: `Params`); structures like this are generally initialized directly in Zig, `init()` being there only when there's also `deinit()`
- Maybe remove TODOs, use more explicit names than `Error1`
- Document public functions
- Expose a similar API for the PHC and Crypt formats.
- Check what should be exported and what should remain local (should `numLen()` be exported? There may be something to do that in the stdlib already, by the way)

**Comment by jedisct1** [comment]
Maybe [this](https://github.com/x13a/zig-scrypt/commit/792aff248d52fb9202f28f9aa14bf0ef804a3c98#r48099806) too?

**Comment by jedisct1** [comment]
Turn `r` and `p` into `u30` since they can't exceed that?

**Comment by jedisct1** [comment]
- Remove allocations in `b64decode` and `b64encode` since the lengths can be known in advance?
- Remove `init()` from `Writer`
- Pretty sure there's no need for `Writer`. Maybe use `std.ArrayList` instead?

**Comment by jedisct1** [comment]
- `ParamsIterator`: should empty values raise an error?
- `PhcEncoding`: what is the `key` for? 
- `PhcEncoding`: this is a generic serialization format, that should support arbitrary key/value pairs. For example, `Argon2` needs a number of threads, memory size, and can have an optional key identifier and additional data. So, the decoding interface should probably directly return an iterator out of a string, and the encoding interface should probably allow incremental updates to an array list.

**Comment by x13a** [comment]
- ~~Turn r and p into u30 since they can't exceed that?~~
- ~~Maybe this too?~~
- ~~Make fromPhcString more strict, return ParseError if parameters are missing~~
- ~~use more explicit names than Error1~~
- ~~should numLen() be exported? There may be something to do that in the stdlib already, by the way)~~
- ~~Remove init() from Writer~~
- ~~ParamsIterator: should empty values raise an error?~~
- ~~PhcEncoding: what is the key for?~~
- ~~Maybe put everything in a single file (perhaps not the PHC serialization)~~
- ~~Pretty sure there's no need for Writer. Maybe use std.ArrayList instead?~~
- ~~PhcEncoding: this is a generic serialization format, that should support arbitrary key/value pairs. For example, Argon2 needs a number of threads, memory size, and can have an optional key identifier and additional data. So, the decoding interface should probably directly return an iterator out of a string, and the encoding interface should probably allow incremental updates to an array list.~~

**Comment by x13a** [comment]
> Remove init() when no allocator is required (ex: Params); structures like this are generally initialized directly in Zig, init() being there only when there's also deinit()

I use this because from my (user) point of view initialize with `Params.init(15, 8, 1)` is more user friendly than `Params{ .log_n = 15, .r = 8, .p = 1 }`. Maybe we can call it something `new` not to expect deinit from it?

Done.

**Comment by x13a** [comment]
> Maybe remove TODOs

Disagree here. `kdf` function have to return `Error!void`. But for now, without `Pbkdf2Error` it can't. This TODO explains that in some time what needs to be done. Of cause they have to be written more correctly than I have done.

Written it more carefully.

**Comment by x13a** [comment]
> PhcEncoding: what is the key for?

Derived key?

**Comment by jedisct1** [comment]
> > Remove init() when no allocator is required (ex: Params); structures like this are generally initialized directly in Zig, init() being there only when there's also deinit()
> 
> I use this because from my (user) point of view initialize with `Params.init(15, 8, 1)` is more user friendly than `Params{ .log_n = 15, .r = 8, .p = 1 }`. Maybe we can call it something `new` not to expect deinit from it?

Yes, it can be a little bit surprising, but that seems to be the common way structures are initialized in Zig, since they can have default values. This is the case for virtually all the structures in the standard library.

**Comment by jedisct1** [comment]
> > PhcEncoding: what is the key for?
> 
> Derived key?

Ah! So maybe call it `dk` (or whatever, but the same way as in the rest of the code)?

In Argon2 and Yescript, for example there's also a `key`, but it has a completely different meaning.

**Comment by x13a** [comment]
> Ah! So maybe call it dk (or whatever, but the same way as in the rest of the code)?

Done. Now it is `derived_key` :)
